spring.application.name=JLingoApp
# This enables the web interface
spring.h2.console.enabled=true

# This sets the URL path
spring.h2.console.path=/h2-console

# This allows the console to be viewed in a frame (Standard for Spring)
spring.headers.frame-options=sameorigin

# Ensure the database name matches what you use to log in
spring.datasource.url=jdbc:h2:mem:jlingodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=